spring.application.name=DigitalBanking
spring.datasource.url=jdbc:postgresql://localhost:5432/DigitalBanking
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=0000
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8082
spring.jpa.hibernate.ddl-auto=update
#pring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always